#ifndef SD1DISK_H
#define SD1DISK_H

/* THIS FILE IS AUTO-GENERATED BY cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* Opaque handles — never dereference these directly in C/C++ code. */
typedef struct DiskImage    DiskImage;
typedef struct DiskImage    Sd1DiskImage;
typedef struct SysExPacket  SysExPacket;
typedef struct SysExPacket  Sd1SysExPacket;
typedef struct Program      Program;
typedef struct Program      Sd1Program;
typedef struct Preset       Preset;
typedef struct Preset       Sd1Preset;
typedef struct Sequence     Sequence;
typedef struct Sequence     Sd1Sequence;

/* File type byte values for sd1_disk_write / sd1_disk_find / Sd1DirectoryEntry.file_type */
#define SD1_FILE_ONE_PROGRAM       ((uint8_t)0x0A)
#define SD1_FILE_SIX_PROGRAMS      ((uint8_t)0x0B)
#define SD1_FILE_THIRTY_PROGRAMS   ((uint8_t)0x0C)
#define SD1_FILE_SIXTY_PROGRAMS    ((uint8_t)0x0D)
#define SD1_FILE_ONE_PRESET        ((uint8_t)0x0E)
#define SD1_FILE_TEN_PRESETS       ((uint8_t)0x0F)
#define SD1_FILE_TWENTY_PRESETS    ((uint8_t)0x10)
#define SD1_FILE_ONE_SEQUENCE      ((uint8_t)0x11)
#define SD1_FILE_THIRTY_SEQUENCES  ((uint8_t)0x12)
#define SD1_FILE_SIXTY_SEQUENCES   ((uint8_t)0x13)
#define SD1_FILE_SYSTEM_EXCLUSIVE  ((uint8_t)0x14)
#define SD1_FILE_SYSTEM_SETUP      ((uint8_t)0x15)
#define SD1_FILE_SEQUENCER_OS      ((uint8_t)0x16)


#define SD1_OK 0

#define SD1_ERR_INVALID_IMAGE -1

#define SD1_ERR_INVALID_SYSEX -2

#define SD1_ERR_WRONG_MSG_TYPE -3

#define SD1_ERR_FILE_NOT_FOUND -4

#define SD1_ERR_FILE_EXISTS -5

#define SD1_ERR_DISK_FULL -6

#define SD1_ERR_DIRECTORY_FULL -7

#define SD1_ERR_BLOCK_OOB -8

#define SD1_ERR_INVALID_TYPE -9

#define SD1_ERR_CORRUPT_FAT -10

#define SD1_ERR_BAD_BLOCK -11

#define SD1_ERR_INVALID_NAME -12

#define SD1_ERR_INVALID_HFE -13

#define SD1_ERR_HFE_CRC -14

#define SD1_ERR_HFE_MISSING_SEC -15

#define SD1_ERR_IO -16

#define SD1_ERR_SLOT59_HAS_DATA -17

/**
 * C-compatible directory entry. Mirrors sd1disk::DirectoryEntry.
 */
typedef struct Sd1DirectoryEntry {
    uint8_t type_info;
    uint8_t file_type;
    char name[12];
    uint16_t size_blocks;
    uint16_t contiguous_blocks;
    uint32_t first_block;
    uint8_t file_number;
    uint32_t size_bytes;
} Sd1DirectoryEntry;

/**
 * C-compatible FAT entry.
 */
typedef struct Sd1FatEntry {
    uint8_t entry_type;
    uint16_t next_block;
} Sd1FatEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return a static human-readable string for any Sd1Error code.
 * The returned pointer is always valid and must never be freed.
 */
const char *sd1_error_message(int32_t code);

/**
 * Open an existing disk image from a file path. Returns NULL on failure;
 * *err_out is set to the error code (may be NULL).
 */
DiskImage *sd1_disk_open(const char *path, int32_t *err_out);

/**
 * Create a blank formatted disk image in memory.
 */
DiskImage *sd1_disk_create(void);

/**
 * Save a disk image to a file. Returns SD1_OK (0) or a negative error code.
 */
int32_t sd1_disk_save(const DiskImage *img, const char *path);

/**
 * Free a DiskImage allocated by sd1_disk_open or sd1_disk_create.
 */
void sd1_disk_free(DiskImage *img);

/**
 * Return the free block count from the OS block.
 */
uint32_t sd1_disk_free_blocks(const DiskImage *img);

/**
 * List all valid directory entries in a subdirectory (subdir 0–3).
 * Returns a heap-allocated array; caller must call sd1_entries_free(ptr, count).
 * Returns NULL on failure; *count_out is set to 0.
 */
struct Sd1DirectoryEntry *sd1_disk_list(const DiskImage *img, uint8_t subdir, uintptr_t *count_out);

/**
 * Find a named file in subdirectory 0–3. Fills *out on success.
 * Returns SD1_OK or SD1_ERR_FILE_NOT_FOUND.
 */
int32_t sd1_disk_find(const DiskImage *img, const char *name, struct Sd1DirectoryEntry *out);

/**
 * Extract raw file data by name. Searches all subdirectories, then block-1.
 * Returns SD1_OK; sets *data_out and *len_out. Caller must call sd1_bytes_free.
 */
int32_t sd1_disk_extract(const DiskImage *img,
                         const char *name,
                         uint8_t **data_out,
                         uintptr_t *len_out);

/**
 * Write a file to the disk image.
 * file_type: a Sd1FileType byte value.
 * programs_embedded: true only for SixtySequences files that include 60 programs.
 * data/len: raw file bytes.
 * overwrite: if true, overwrite an existing file with the same name.
 * Returns SD1_OK or a negative error code.
 */
int32_t sd1_disk_write(DiskImage *img,
                       const char *name,
                       uint8_t file_type_byte,
                       bool programs_embedded,
                       const uint8_t *data,
                       uintptr_t len,
                       bool overwrite);

/**
 * Delete a file by name. Frees FAT chain and removes directory entry.
 * Returns SD1_OK or a negative error code.
 */
int32_t sd1_disk_delete(DiskImage *img, const char *name);

/**
 * List VST3 block-1 directory entries. Caller must call sd1_entries_free.
 */
struct Sd1DirectoryEntry *sd1_block1_entries(const DiskImage *img, uintptr_t *count_out);

/**
 * Find a named file in the VST3 block-1 directory. Fills *out on success.
 */
int32_t sd1_block1_find(const DiskImage *img, const char *name, struct Sd1DirectoryEntry *out);

/**
 * Return the next file_number to assign for a given file type byte.
 */
uint8_t sd1_next_file_number(const DiskImage *img, uint8_t file_type_byte);

/**
 * Return the type_info byte for a directory entry.
 */
uint8_t sd1_file_type_info(uint8_t file_type_byte, bool programs_embedded);

/**
 * Validate a name and write the 11-byte space-padded form into out[11].
 * Returns SD1_OK or SD1_ERR_INVALID_NAME.
 */
int32_t sd1_validate_name(const char *name, uint8_t *out);

/**
 * Read a .hfe file and return a DiskImage. Returns NULL on failure.
 */
DiskImage *sd1_read_hfe(const char *path, int32_t *err_out);

/**
 * Write a DiskImage as a .hfe file. Returns SD1_OK or a negative error code.
 */
int32_t sd1_write_hfe(const DiskImage *img, const char *path);

/**
 * Read a FAT entry for the given block. Fills *out.
 */
void sd1_fat_entry(const DiskImage *img, uint16_t block, struct Sd1FatEntry *out);

/**
 * Walk a FAT chain starting at `start`. Returns a heap-allocated array of block numbers.
 * Caller must call sd1_u16_array_free(ptr, count). Returns NULL on error.
 */
int32_t sd1_fat_chain(const DiskImage *img,
                      uint16_t start,
                      uint16_t **blocks_out,
                      uintptr_t *count_out);

/**
 * Allocate n free blocks. Returns a heap-allocated array.
 * Caller must call sd1_u16_array_free(ptr, count). Returns NULL on error.
 */
int32_t sd1_fat_allocate(DiskImage *img, uint16_t n, uint16_t **blocks_out, uintptr_t *count_out);

/**
 * Free an entire FAT chain starting at `start`.
 */
void sd1_fat_free_chain(DiskImage *img, uint16_t start);

/**
 * Write a FAT chain from an array of block numbers.
 */
void sd1_fat_set_chain(DiskImage *img, const uint16_t *blocks, uintptr_t count);

/**
 * Count free data blocks (blocks 23–1599).
 */
uint32_t sd1_fat_count_free(const DiskImage *img);

/**
 * Parse a single SysEx packet. Returns NULL on failure.
 */
SysExPacket *sd1_sysex_parse(const uint8_t *data, uintptr_t len, int32_t *err_out);

/**
 * Parse all SysEx packets from a byte stream.
 * Returns a heap-allocated array of pointers. Caller must call sd1_sysex_packets_free.
 * Returns NULL on failure; *count_out set to 0.
 */
SysExPacket **sd1_sysex_parse_all(const uint8_t *data,
                                  uintptr_t len,
                                  uintptr_t *count_out,
                                  int32_t *err_out);

/**
 * Return the message type byte of a SysEx packet.
 */
uint8_t sd1_sysex_message_type(const SysExPacket *pkt);

/**
 * Return the MIDI channel of a SysEx packet.
 */
uint8_t sd1_sysex_midi_channel(const SysExPacket *pkt);

/**
 * Return the model byte of a SysEx packet.
 */
uint8_t sd1_sysex_model(const SysExPacket *pkt);

/**
 * Return a pointer to the payload bytes of a SysEx packet. Do not free this pointer.
 */
const uint8_t *sd1_sysex_payload(const SysExPacket *pkt);

/**
 * Return the payload length of a SysEx packet.
 */
uintptr_t sd1_sysex_payload_len(const SysExPacket *pkt);

/**
 * Serialize a SysEx packet to bytes on the given channel.
 * Caller must call sd1_bytes_free(ptr, len).
 */
uint8_t *sd1_sysex_to_bytes(const SysExPacket *pkt, uint8_t channel, uintptr_t *len_out);

/**
 * Free a SysExPacket allocated by sd1_sysex_parse or similar.
 */
void sd1_sysex_free(SysExPacket *pkt);

/**
 * Free an array of SysExPacket pointers from sd1_sysex_parse_all.
 */
void sd1_sysex_packets_free(SysExPacket **pkts, uintptr_t count);

/**
 * Parse a Program from a SysEx packet. Returns NULL on failure.
 */
Program *sd1_program_from_sysex(const SysExPacket *pkt, int32_t *err_out);

/**
 * Parse a Program from raw bytes. Returns NULL on failure.
 */
Program *sd1_program_from_bytes(const uint8_t *data, uintptr_t len, int32_t *err_out);

/**
 * Return raw bytes for the program. Caller must free with sd1_bytes_free(data, len).
 */
uint8_t *sd1_program_bytes(const Program *prog, uintptr_t *len_out);

/**
 * Write the program name (null-terminated) into out[0..out_len].
 */
void sd1_program_name(const Program *prog, char *out, uintptr_t out_len);

/**
 * Convert a Program to a SysEx packet. Returns NULL on error (never in practice).
 */
SysExPacket *sd1_program_to_sysex(const Program *prog, uint8_t channel);

/**
 * Return the file type byte for a Program.
 */
uint8_t sd1_program_file_type(const Program *prog);

/**
 * Free a Program allocated by sd1_program_from_sysex or sd1_program_from_bytes.
 */
void sd1_program_free(Program *prog);

/**
 * Parse a Preset from a SysEx packet. Returns NULL on failure.
 */
Preset *sd1_preset_from_sysex(const SysExPacket *pkt, int32_t *err_out);

/**
 * Parse a Preset from raw bytes. Returns NULL on failure.
 */
Preset *sd1_preset_from_bytes(const uint8_t *data, uintptr_t len, int32_t *err_out);

/**
 * Return raw bytes for the preset. Caller must free with sd1_bytes_free(data, len).
 */
uint8_t *sd1_preset_bytes(const Preset *preset, uintptr_t *len_out);

/**
 * Convert a Preset to a SysEx packet.
 */
SysExPacket *sd1_preset_to_sysex(const Preset *preset, uint8_t channel);

/**
 * Return the file type byte for a Preset.
 */
uint8_t sd1_preset_file_type(const Preset *preset);

/**
 * Free a Preset.
 */
void sd1_preset_free(Preset *preset);

/**
 * Parse a Sequence from a SysEx packet. Returns NULL on failure.
 */
Sequence *sd1_sequence_from_sysex(const SysExPacket *pkt, int32_t *err_out);

/**
 * Create a Sequence from raw bytes.
 */
Sequence *sd1_sequence_from_bytes(const uint8_t *data, uintptr_t len);

/**
 * Return raw bytes for the sequence. Caller must free with sd1_bytes_free(data, len).
 */
uint8_t *sd1_sequence_bytes(const Sequence *seq, uintptr_t *len_out);

/**
 * Convert a Sequence to a SysEx packet.
 */
SysExPacket *sd1_sequence_to_sysex(const Sequence *seq, uint8_t channel);

/**
 * Return the file type byte for a Sequence.
 */
uint8_t sd1_sequence_file_type(const Sequence *seq);

/**
 * Free a Sequence.
 */
void sd1_sequence_free(Sequence *seq);

/**
 * Convert an AllSequences SysEx payload + interleaved program data to on-disk format.
 * If interleaved_progs is NULL, programs are not embedded.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_allsequences_to_disk(const uint8_t *payload,
                                 uintptr_t payload_len,
                                 const uint8_t *interleaved_progs,
                                 uintptr_t progs_len,
                                 uint8_t **out,
                                 uintptr_t *out_len);

/**
 * Convert on-disk SixtySequences data to a lossless library-format AllSequences SysEx payload.
 * Output: ptr table (240) + 12 lead zeros + packed event data + 60 × 186-byte headers + 29-byte global.
 * This is the raw payload format, not framed or nibble-encoded; it feeds into allsequences_to_disk.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_disk_to_allsequences(const uint8_t *disk,
                                 uintptr_t len,
                                 bool has_programs,
                                 uint8_t **out,
                                 uintptr_t *out_len);

/**
 * Convert on-disk ThirtySequences data to a lossless library-format AllSequences SysEx payload.
 * Slots 0–29 come from disk; slots 30–59 are set to undefined (0xFF headers).
 * Output is the raw 60-slot payload (ptr table + event data + headers + global), not framed.
 * Programs embedded after sequence data (if any) are not included in the output.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_disk_to_thirty_sequences(const uint8_t *disk,
                                     uintptr_t len,
                                     uint8_t **out,
                                     uintptr_t *out_len);

/**
 * Convert on-disk SixtySequences data to a hardware-compatible SD-1 AllSequences SysEx
 * (F0 0F 05 00 00 0A … F7, nibble-encoded), ready to send to a real SD-1 in load mode.
 * Sequence slot 59 is always undefined in hardware SysEx format (hardware limitation).
 * If slot 59 has sequence data and allow_slot59_loss is false, returns SD1_ERR_SLOT59_HAS_DATA.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_disk_to_allsequences_hw_sysex(const uint8_t *disk,
                                          uintptr_t len,
                                          bool has_programs,
                                          bool allow_slot59_loss,
                                          uint8_t **out,
                                          uintptr_t *out_len);

/**
 * Convert on-disk ThirtySequences data to a hardware-compatible SD-1 AllSequences SysEx.
 * Slots 0–29 from disk; slots 30–59 undefined. Slot 59 hardware limitation applies.
 * If slot 59 has sequence data and allow_slot59_loss is false, returns SD1_ERR_SLOT59_HAS_DATA.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_disk_to_thirty_sequences_hw_sysex(const uint8_t *disk,
                                              uintptr_t len,
                                              bool allow_slot59_loss,
                                              uint8_t **out,
                                              uintptr_t *out_len);

/**
 * Convert an AllSequences SysEx payload to on-disk ThirtySequences format.
 * Only slots 0–29 are written; slots 30–59 are ignored.
 * Programs (if any) are placed AFTER sequence data (opposite of SixtySequences layout).
 * If interleaved_progs is NULL, programs are not embedded.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_thirty_sequences_to_disk(const uint8_t *payload,
                                     uintptr_t payload_len,
                                     const uint8_t *interleaved_progs,
                                     uintptr_t progs_len,
                                     uint8_t **out,
                                     uintptr_t *out_len);

/**
 * Convert an AllSequences SysEx file to on-disk SixtySequences format,
 * auto-detecting hardware RAM dump vs library-generated SysEx.
 * Hardware dumps have a non-zero base RAM address in ptr_table[0]; library-
 * generated files have zero. Multi-message files are supported.
 * If interleaved_progs is NULL, programs are not embedded.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_allsequences_sysex_to_disk(const uint8_t *raw,
                                       uintptr_t raw_len,
                                       const uint8_t *interleaved_progs,
                                       uintptr_t progs_len,
                                       uint8_t **out,
                                       uintptr_t *out_len);

/**
 * Nibble-decode a hardware SD-1 SysEx data section.
 * `(hi << 4) | lo` for each consecutive pair. Output len = input len / 2 (truncated).
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_decode_sysex_nibbles(const uint8_t *data,
                                 uintptr_t len,
                                 uint8_t **out,
                                 uintptr_t *out_len);

/**
 * Convert a hardware AllSequences SysEx dump to SD-1 on-disk SixtySequences format.
 * Multi-message files (e.g. from SysEx Librarian) are supported; the first 0x0A message is used.
 * If interleaved_progs is NULL, programs are not embedded.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_allsequences_hardware_sysex_to_disk(const uint8_t *raw,
                                                uintptr_t raw_len,
                                                const uint8_t *interleaved_progs,
                                                uintptr_t progs_len,
                                                uint8_t **out,
                                                uintptr_t *out_len);

/**
 * Interleave 60 programs from AllPrograms SysEx payload order to on-disk SixtyPrograms format.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_interleave_sixty_programs(const uint8_t *payload,
                                      uintptr_t len,
                                      uint8_t **out,
                                      uintptr_t *out_len);

/**
 * De-interleave on-disk SixtyPrograms data back to AllPrograms SysEx payload order.
 * Caller must call sd1_bytes_free(*out, *out_len).
 */
int32_t sd1_deinterleave_sixty_programs(const uint8_t *data,
                                        uintptr_t len,
                                        uint8_t **out,
                                        uintptr_t *out_len);

/**
 * Decode a program name from a 530-byte slot. Writes null-terminated name into out[0..out_len].
 */
void sd1_program_name_from_slot(const uint8_t *slot,
                                uintptr_t slot_len,
                                char *out,
                                uintptr_t out_len);

/**
 * Decode a b10 track program assignment byte to a human-readable label.
 * disk_programs: optional array of count C-string pointers (NULL = use INT0 defaults).
 * Writes null-terminated result into out[0..out_len].
 */
void sd1_decode_b10(uint8_t b10,
                    const char *const *disk_programs,
                    uintptr_t count,
                    char *out,
                    uintptr_t out_len);

/**
 * Return pointer to the 60-entry INT0 user bank name table.
 * Each entry is a null-terminated C string; never free any pointer.
 * Returns a pointer to an array of 60 `const char*` pointers.
 */
const char *const *sd1_int0_programs(void);

/**
 * Return pointer to the 120-entry ROM name table.
 * Each entry is a null-terminated C string; never free any pointer.
 * Returns a pointer to an array of 120 `const char*` pointers.
 */
const char *const *sd1_rom_all_programs(void);

/**
 * Free a Sd1DirectoryEntry array from sd1_disk_list or sd1_block1_entries.
 */
void sd1_entries_free(struct Sd1DirectoryEntry *ptr, uintptr_t count);

/**
 * Free a byte buffer from sd1_disk_extract, sd1_sysex_to_bytes, or conversion functions.
 */
void sd1_bytes_free(uint8_t *ptr, uintptr_t len);

/**
 * Free a u16 array from sd1_fat_chain or sd1_fat_allocate.
 */
void sd1_u16_array_free(uint16_t *ptr, uintptr_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SD1DISK_H */
